from . import res_company
from . import op_department
from . import course
from . import course_category
from . import cast_category
from . import op_casts
from . import mother_tongue
from . import religion
from . import op_student
